### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by maslof** [capistrano/passenger#13]
How translate from global error.log in rails production.log?

**Comment by betesh** [comment]
I am not sure what your question is.  Can you please explain?  Thank you.

**Comment by maslof** [comment]
"By default Phusion Passenger log messages are written to the global web server error log.". 
All messages from rails production write in error.log nginx, but production.log in rails app is empty. How fix?

**Comment by betesh** [comment]
This is the wrong project to be asking that question on.  I think you are looking for https://github.com/phusion/passenger
