### ISSUE TITLE
Using rvm but passenger is installed as an nginx module

### ISSUE THREAD

**Issue by mjdavies** [capistrano/passenger#21]
Morning all

I've got a probably non standard setup.

I install nginx from source, and during that install add the passenger module, by pointing it at a downloaded passenger source code.  I find it easier to upgrade nginx and passenger like this.

I'm using passenger 5 and running multiple apps with different rubies, installed via rvm.

I can't seem to get the restart to work.

First of all it was saying that passenger isn't installed.  Ok, so I added the path to my source to /etc/profile.d

On the server as the same user that does the deploy, if I run which passenger I get a reply.

/src/passenger-5.0.7/bin/passenger

But the restart keeps on failing

[8ae70cfc] Running /usr/bin/env which passenger as topdog@railsstage4.it.southwales.ac.uk
DEBUG [8ae70cfc] Command: /usr/bin/env which passenger
DEBUG [8ae70cfc] Finished in 0.641 seconds with exit status 1 (failed).

I know it must be extremely difficult to get this to work with all our crazy differences, but should I persevere here, and keep on trying all the different options?  Or, just accept that it's not ready for this type of setup, and touch tmp/restart.txt?

I'd like to use the new stuff, but I'm struggling.  If anyone has worked this out I'm all ears.

Regards

Matt

**Comment by betesh** [comment]
Try using the latest master branch instead of the rubygem.  Let me know if that solves the problem.  I plan to release another ruby gem within the next day or two--I'm just waiting for some feedback first.

As you said, there are a lot of different environments, and trying to handle all of them without requiring a lot of configuration is not easy.  One thing to be aware of, however, is that it's ok if `which passenger` fails--that just tells us if we need to prefix it on the command map when we attempt to use it later.  Instead of adding it to /etc/profile.d, try this:

set :passenger_environment_variables, { PATH: "/src/passenger-5.0.7/bin/" }

**Comment by mjdavies** [comment]
Hi, thanks for getting back to me.

I tried your suggestion, using the master git branch, but still no luck.

I think I'm getting my head around it all a bit more now

Here's the final error this time.

```
Running ~/.rvm/bin/rvm ruby-2.2.2@corptrain do passenger -v as topdog@railsstage4.it.southwales.ac.uk
DEBUG [b39d4456] Command: cd /var/www/rails/corptrain/releases/20150603125811 && ( PATH=/src/passenger-5.0.7/bin:$PATH ~/.rvm/bin/rvm ruby-2.2.2@corptrain do passenger -v )
DEBUG [b39d4456]    Phusion Passenger version 5.0.7
DEBUG [b39d4456]
DEBUG [b39d4456]    "Phusion Passenger" is a trademark of Hongli Lai & Ninh Bui.
DEBUG [b39d4456] Finished in 0.322 seconds with exit status 0 (successful).
INFO [2c5db074] Running ~/.rvm/bin/rvm ruby-2.2.2@corptrain do passenger-config restart-app /var/www/rails/corptrain --ignore-app-not-running as topdog@railsstage4.it.southwales.ac.uk
DEBUG [2c5db074] Command: cd /var/www/rails/corptrain/releases/20150603125811 && ( PATH=/src/passenger-5.0.7/bin:$PATH ~/.rvm/bin/rvm ruby-2.2.2@corptrain do passenger-config restart-app /var/www/rails/corptrain --ignore-app-not-running )
DEBUG [2c5db074]    *** ERROR: You are not authorized to query the status for this Phusion Passenger instance. Please try again with 'rvmsudo'.
```

I feel I'm much closer now.

I tried telling it to use sudo by setting passenger_restart_with_sudo set as true, but that failed like so.

```
[c25b92c2] Command: cd /var/www/rails/corptrain/releases/20150603132433 && ( PATH=/src/passenger-5.0.7/bin:$PATH /usr/bin/env sudo passenger-config restart-app /var/www/rails/corptrain --ignore-app-not-running )
DEBUG [c25b92c2]    sudo: passenger-config: command not found
```

So I then tried changing the restart command to this

```
set :passenger_restart_command, '/src/passenger-5.0.7/bin/passenger-config restart-app'
```

That then failed like this

```
INFO [85ab5f9c] Running /usr/bin/env sudo /src/passenger-5.0.7/bin/passenger-config restart-app /var/www/rails/corptrain --ignore-app-not-running as topdog@railsstage4.it.southwales.ac.uk
DEBUG [85ab5f9c] Command: cd /var/www/rails/corptrain/releases/20150603132621 && ( PATH=/src/passenger-5.0.7/bin:$PATH /usr/bin/env sudo /src/passenger-5.0.7/bin/passenger-config restart-app /var/www/rails/corptrain --ignore-app-not-running )
DEBUG [85ab5f9c]    /usr/bin/env:
DEBUG [85ab5f9c]    ruby
DEBUG [85ab5f9c]    : No such file or directory
```

As I mentioned previously, this must be extremely difficult to get working for everyone, and if I comment all of those passenger options out and use 

set :passenger_restart_with_touch, true

It all works fine, so I don't want to be too much of a pain in the arse.

Feels like I'm close though :-)

Thanks again.

**Comment by betesh** [comment]
One more suggestion:

```
set(:rvm_map_bins) , fetch(:rvm_map_bins) << :rvmsudo
set :passenger_restart_command, 'rvmsudo /src/passenger-5.0.7/bin/passenger-config restart-app'
```

**Comment by mjdavies** [comment]
Thanks for trying betesh, but those suggestions didn't work either.

I think it may be tied into the fact that RVM is a user install, and not a system install.  Also there's no passenger gem on the server, that seems to be causing an issue, and also finding ruby when you are sudo isn't working, or rvmsudo.

I've got it working using the old methodology, as set :passenger_restart_with_touch, true isn't working now either, I think yesterday I had a manual restart in there so it was confusing me.

Like I said, thanks for trying.

**Comment by betesh** [comment]
Is this still happening with v0.1.1?

**Comment by jiehanzheng** [comment]
Seems that adding

``` ruby
set :default_env, { path: "/usr/local/bin/:$PATH" }
```

fixes it :)

**Comment by will-in-wi** [comment]
This is an old ticket, and it sounds like there is a workaround. I'm closing it. Feel free to reopen if the original issue still exists.
