### ISSUE TITLE
Deploy fails with rbenv -- passenger command not found

### ISSUE THREAD

**Issue by Limb** [capistrano/passenger#22]
Hello,

I'm trying to deploy to a ubuntu server using the passenger-nginx apt repository. I'm using rbenv on the server to manage ruby. However when I try and deploy I can't get past what I think is the initial passenger command check. The error I'm getting is:

```
DEBUG [80178d9e] Command: ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.2 ~/.rbenv/bin/rbenv exec passenger -v )
DEBUG [80178d9e]    rbenv: passenger: command not found
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@www.logicfivetech.com: passenger exit status: 127
passenger stdout: Nothing written
passenger stderr: rbenv: passenger: command not found

SSHKit::Command::Failed: passenger exit status: 127
passenger stdout: Nothing written
passenger stderr: rbenv: passenger: command not found

Tasks: TOP => passenger:restart
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@www.logicfivetech.com: passenger exit status: 127
passenger stdout: Nothing written
passenger stderr: rbenv: passenger: command not found
```

The passenger command works fine on the command line. Is there a option I'm missing to have the passenger restart commands to run outside of the rbenv environment?

**Comment by betesh** [comment]
Run `which passenger` on the server and put the output here.  Is it installed via RBenv or apt-get/yum?

**Comment by Limb** [comment]
Output for `which passenger` is:

```
deploy@www:~$ which passenger
/usr/bin/passenger
```

Passenger was install via apt-get.

**Comment by betesh** [comment]
In that case, the problem is that if you're using capistrano-rbenv, capistrano-passenger assumes passenger was installed that way.  Take a look at task `passenger:rvm:hook` in the source and implement something similar for RBEnv in a PR.

Our CHRuby hook is going to have the same issue.  Feel free to address it in the same PR.
