### ISSUE TITLE
Errors when restarting via cap but restarts ok when I ssh in...

### ISSUE THREAD

**Issue by kule** [capistrano/passenger#32]
Hey @betesh 

Sorry to bother you but I don't suppose you'd have any ideas on what would be causing this?  I can't restart the app via capistrano but if I ssh in using the deploy user the restart command works

I'm using the current versions of the cap gems:

```
capistrano (3.4.0)
capistrano-bundler (1.1.4)
capistrano-passenger (0.1.1)
capistrano-rails (1.1.3)
capistrano-rvm (0.1.2)
```

I'm taking over a rails 3.1 app that currently doesn't use the asset pipeline if that makes any difference - using ruby 2.0.0-p645

```
INFO [41d72b26] Running /usr/bin/env /usr/bin/env passenger-config restart-app /home/deployuser/public_html/mysite.com --ignore-app-not-running as deployuser@deployserver.com
DEBUG [41d72b26] Command: /usr/bin/env passenger-config restart-app /home/deployuser/public_html/mysite.com --ignore-app-not-running
DEBUG [41d72b26]  /usr/lib/ruby/vendor_ruby/phusion_passenger/config/restart_app_command.rb:24:in `require': no such file to load -- optparse
DEBUG [41d72b26]   (LoadError)
DEBUG [41d72b26]    from /usr/lib/ruby/vendor_ruby/phusion_passenger/config/restart_app_command.rb:24
DEBUG [41d72b26]    from /usr/lib/ruby/vendor_ruby/phusion_passenger.rb:235:in `require'
```

I'm guessing it's an environment issue but not sure how to rectify it...

Thanks
Luke

**Comment by betesh** [comment]
What version of passenger are you running on the server?

**Comment by kule** [comment]
5.0.15

**Comment by betesh** [comment]
Does this command work when run on the server?

```
usr/bin/env passenger-config restart-app /home/deployuser/public_html/physiopilates.co.uk --ignore-app-not-running
```

**Comment by kule** [comment]
Yep: `Restarting /home/deployuser/public_html/mysite.com/current/public (production)`

**Comment by betesh** [comment]
Where / How is Ruby installed (i.e. RVM, RBEnv, etc.)?

**Comment by kule** [comment]
Installed via rvm:

```
> rvm --version
rvm 1.26.11 (latest)

> which ruby
/home/deployuser/.rvm/rubies/ruby-2.0.0-p645/bin/ruby
```

**Comment by betesh** [comment]
I suspect what's happening is that passenger was installed without RVM, but optparse was installed with RVM.  Try this:

```
set(:passenger_restart_command) { "rvm #{fetch(:rvm_ruby_version)} do passenger-config restart-app" }
```

It should give your passenger command access to any of Ruby that's installed via RVM.

**Comment by kule** [comment]
That's got it!  Thank you!!

Yep I installed passenger using the debian packages; strange the same setup works ok on another server though...

**Comment by kule** [comment]
Hey just wanted to say thank you very much for yesterday - really helped me out at the end of a very long day!  Was gonna send you a voucher of some kind but I have no idea what country you're in or contact details (you're github profile is pretty light ha) - so anyways - if you wanna choose something nice off https://pragprog.com or http://www.redbubble.com/shop/ruby+on+rails#_ or something more your thing let me know - it's my shout. Cheers Luke
