### ISSUE TITLE
Could not find 'passenger' on Debian

### ISSUE THREAD

**Issue by manno** [capistrano/passenger#39]
I'm trying to deploy to a Debian Jessie host, using the passenger from Debians 'ruby-passenger' package. The application itself uses Ruby 2.3.0 from rvm, if I read the rvm documentation correctly this should be possible?

But `cap deploy` fails with 

```
SSHKit::Command::Failed: passenger exit status: 127
passenger stdout: Nothing written
passenger stderr: /home/frab/.rvm/scripts/set: line 19: exec: passenger: not found
```

There is no `passenger` binary included in the Debian package at all: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793013

**Comment by betesh** [comment]
If there's no binary, then I'm not sure how the package maintainers expect you to use it.  Please find out what command you are supposed to use to start the passenger process from that package and then consult capistrano-passenger's README for how to configure it to use that command.

**Comment by manno** [comment]
I guess most Debian users [use the .deb file from passenger](https://www.phusionpassenger.com/library/install/nginx/install/oss/jessie/).
I wrote a short capistrano task to touch the `restart.txt`, since that was all I needed.
