### ISSUE TITLE
PSA: passenger from Ubuntu 16.04 repo does not provide /usr/bin/passenger

### ISSUE THREAD

**Issue by dmke** [capistrano/passenger#41]
I just stumbled over this:

The Ubuntu native package [passenger](http://packages.ubuntu.com/xenial/passenger) (5.0.27-2) doesn't provide a `passenger` binary. This is relevant, if `fetch(:passenger_restart_with_touch)` is `nil`, i.e. you don't have an explicit

``` ruby
set :passenger_restart_with_touch, false # or true
```

in your Capistrano configuration. Otherwise [`capture(:passenger, '-v')`](https://github.com/capistrano/passenger/blob/v0.2.0/lib/capistrano/tasks/passenger.cap#L20) will be executed and fail with

```
SSHKit::Runner::ExecuteError: Exception while executing on host xxx: passenger exit status: 127
passenger stdout: Nothing written
passenger stderr: /usr/bin/env: 'passenger': No such file or directory
```

**Comment by betesh** [comment]
Duplicates #39.  PR welcome, if you know what the proper command would be to restart passenger in this case.

**Comment by dmke** [comment]
Oh, I didn't see #39, sorry for the noise.

Restarting is not a problem, as `/usr/bin/passenger-config` _does_ exist.

**Comment by betesh** [comment]
Is there a guarantee as to what version of passenger is running in this situation?
Is there a command we could run to detect this situation?

**Comment by dmke** [comment]
No, not really.
- Ubuntu ships [passenger (5.0.27-2)](http://packages.ubuntu.com/xenial/passenger) since Xenial (16.04 LTS)
- Debian ships
  - [ruby-passenger (4.0.53-1)](https://packages.debian.org/jessie/ruby-passenger) in Stable (Jessie/8)
  - [passenger (5.0.27-2)](https://packages.debian.org/stretch/passenger) in Testing (Stretch/9)

Neither has a `passenger` binary, but a `passenger-config` (except Debian Stable, of course).

I've made a conscious decision and set `:passenger_restart_with_touch` in the `config/deploy.rb`.

**Comment by dmke** [comment]
I mean, one could first check with `which passenger`, whether the `passenger` binary exists and if not, decide whether or not to use touch-restart by checking the existence of `passenger-config`.

But I don't know how well that would work, if `sudo` is involved...
