### ISSUE TITLE
Passenger-restart happens on previous release, not the one that is just deployed

### ISSUE THREAD

**Issue by premnirmal** [capistrano/passenger#43]
I noticed that the `passenger:restart` task restarts the previous revision of the app, and not the one just deployed.

This is the output when I run `cap production deploy`
```
...
...
00:35 deploy:symlink:release
      01 ln -s /var/www/appname/releases/20170513151848 /var/www/appname/…
    ✔ 01 user@xxxxxx 0.223s
      02 mv /var/www/appname/releases/current /var/www/appname
    ✔ 02 user@xxxxxx 0.214s
00:36 passenger:restart
      01 passenger-config restart-app /var/www/appname --ignore-app-not-running
      01 Restarting /var/www/appname/releases/20170513143827/public (production)
    ✔ 01 user@xxxxxx 0.416s
00:36 deploy:restart_redis
...
...
```
Notice that the `Restarting /var/www/appname/releases/20170513143827/public` has a different release to the one that was just deployed (`20170513151848`).

This is my nginx config for the app:
```
server {
	listen 80 default;
	listen [::]:80;

	# SSL configuration
	ssl on;
	listen 443 ssl;
       # Server config
	server_name www.servername.com;
	root /var/www/appname/current/public;
...
...
```

Here is my capfile:
``` ruby
# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Include capistrano-rails
require 'capistrano/rails'
require 'capistrano/rvm'
require 'capistrano/bundler'
require 'capistrano/rails/migrations'
require 'capistrano/rails/assets'

require 'capistrano/bundler'
require 'capistrano/passenger'

# Load the SCM plugin appropriate to your project:
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }

```

My gem file: (running rails 5)
``` ruby
group :development do
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  # gem 'spring'
  # gem 'spring-watcher-listen', '~> 2.0.0'
  # Capistrano for deployment
  gem 'capistrano', '~> 3.6'
  gem 'capistrano-rails', '~> 1.1'
  gem 'capistrano-rvm', '~> 0.1.0'
  gem 'capistrano-bundler'
  gem 'capistrano-passenger', '>= 0.1.1'
end
```

The task is not using the correct revision of the app to deploy.

**Comment by betesh** [comment]
capistrano-passenger is running the right command in the output above, so this is either an error in your configuration or a bug in passenger itself.

Here are a few questions that might help you debug it:

Did this work at some point in the past?  If so, what gems did you upgrade that made it stop working?

Does adding this line to your nginx config fix it:

```
passenger_app_root /var/www/appname/current
```

Do you have any other websites running under passenger in the same directory?

**Comment by premnirmal** [comment]
Thanks for your response @betesh 

I believe this is a bug related to `capistrano-passenger` because it is not picking the correct release directory in the `restart:passenger` task.
To answer your questions:
> Did this work at some point in the past? If so, what gems did you upgrade that made it stop working?
- I only noticed this bug recently, but it was probably happening since my initial setup . I didn't upgrade any gems
> Does adding this line to your nginx config fix it:
`passenger_app_root /var/www/appname/current`
- I added that and re-deployed, but same issue, see the output:
```
00:33 deploy:symlink:release
      01 ln -s /var/www/myapp/releases/20170516011114 /var/www/robindahood.com/…
    ✔ 01 user@xxxxxx 0.210s
      02 mv /var/www/myapp/releases/current /var/www/robindahood.com
    ✔ 02 user@xxxxxx 0.233s
00:34 passenger:restart
      01 passenger-config restart-app /var/www/myapp --ignore-app-not-running
      01 Restarting /var/www/myapp/releases/20170513143827/public (production)
    ✔ 01 user@xxxxxx 0.385s
00:34 deploy:restart_redis
```
You can see above that it is still restarting a very old version (not even the previous version), it is restarting the version from 3 days ago (`20170513143827`) and not the newly deployed version `20170516011114`. Check the timestamps ^^
> Do you have any other websites running under passenger in the same directory?
- Nope, just this one.

**Comment by premnirmal** [comment]
Same issue for this person too: https://discussion.dreamhost.com/thread-119481-post-142045.html#pid142045

**Comment by betesh** [comment]
Notice these 2 lines of output:
```
01 passenger-config restart-app /var/www/myapp --ignore-app-not-running
01 Restarting /var/www/myapp/releases/20170513143827/public (production)
```

The first is coming from capistrano, logging that it is running the correct command from capistrano-passenger.  That command looks correct to me.

The next line is coming from passenger (probably [here](https://github.com/phusion/passenger/blob/7eb5f0e9da983fb034a77f02a3a7b21708fd29ae/src/ruby_supportlib/phusion_passenger/config/restart_app_command.rb#L222) and it somehow selected the wrong directory to restart.

In the dreamhost discussion you linked to, it is also very clear that it was a bug in passenger (from 2011, before capistrano-passenger existed).

Turn the log level up to debug and maybe that will tell us more...
