### ISSUE TITLE
Upgrade to 0.0.3 causes error with rvm:hook

### ISSUE THREAD

**Issue by floydj** [capistrano/passenger#5]
My Capfile:

```
require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/rbenv'
require 'capistrano/rails'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
require 'capistrano/passenger'

# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
```

After upgrading to 0.0.3, when I to do a `cap production deploy` I get:

```
(Backtrace restricted to imported tasks)
cap aborted!
Don't know how to build task 'rvm:hook'
/path/to/my/app/Capfile:8:in `<top (required)>'
LoadError: cannot load such file -- capistrano/passenger
/path/to/my/app/Capfile:8:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by betesh** [comment]
Interesting.  I had thought that if I define an after hook and the task it hooks onto isn't defined, it will simply have no effect, but I guess that is not the case.  I will look into how we can work around this so that if you are not using rvm, the hook has no effect, and will release an updated gem as soon as I have a solution.

**Comment by betesh** [comment]
@floydj Can you try again with the latest push to master and confirm that it works?  As soon as someone not using RVM can confirm that this works, I will release a new gem with this fix.

Since I see that you are also using rbenv, please let me know whether it needs a similar hook to the one I defined for rvm.

**Comment by jaredbeck** [comment]
I'm not using RVM, and I can confirm that 0.0.3 fails for me too.

```
cap aborted!
Don't know how to build task 'rvm:hook'
/Users/redacted/Capfile:23:in `require'
/Users/redacted/Capfile:23:in `<top (required)>'
```

> Can you try again with the latest push to master ..

Will do.

**Comment by jaredbeck** [comment]
> Can you try again with the latest push to master ..

Master branch works for me, thanks.

**Comment by floydj** [comment]
I'm still getting the `Don't know how to build task 'rvm:hook'` error after using master.  Am I missing something here?

**Comment by jaredbeck** [comment]
Floyd, Are you sure you ran `bundle update capistrano-passenger`?  If so, you should have a line like "capistrano-passenger!" (note the exclamation point) in your Gemfile.lock.

My Gemfile has:

```
gem 'capistrano-passenger', require: false, github: 'capistrano/passenger'
```

**Comment by floydj** [comment]
I have that exact line in my Gemfile, and I have the exclamation point in the Gemfile.lock file.

I still get the same rvm:hook error.

**Comment by jaredbeck** [comment]
What does `grep -B 1 -A 5 'github.com/capistrano/passenger' Gemfile.lock` print?

**Comment by floydj** [comment]
```
  remote: git://github.com/capistrano/passenger.git
  revision: 3c3bb4c7534d128bca2b89b24af6805430657636
  specs:
    capistrano-passenger (0.0.3)
      capistrano (~> 3.0)
```

**Comment by jaredbeck** [comment]
That's the right SHA, you're definitely using `master`.  I'm not sure what else to suggest.  Maybe you can get a better stack trace somehow?

**Comment by floydj** [comment]
Running it with a trace shows this line:

`LoadError: cannot load such file -- capistrano/passenger`

I don't understand that - it should be there since the gem's installed, right?

**Comment by betesh** [comment]
Since @jaredbeck has confirmed that commit 3c3bb4c75 solves the issue for him, I am going to release a new gem.

**Comment by betesh** [comment]
Done.

**Comment by floydj** [comment]
The new gem fixed it for me.  Not sure why the pull from master didn't.  Thanks to all!
