### ISSUE TITLE
undefined method `[]' for nil:NilClass after upgraging Passenger to 6.0.8

### ISSUE THREAD

**Issue by mrusa** [capistrano/passenger#52]
This is the same problem already addressed in #36. The new Passenger version 6.0.8, released yesterday, has a new output when calling `passenger -v`, so the regex in https://github.com/capistrano/passenger/blob/master/lib/capistrano/tasks/passenger.cap#L20 does not work anymore.

For me, a temporary fix was to add `set :passenger_restart_with_touch, false` to my `deploy.rb` so the regex won't get called.

**Comment by dheroying** [comment]
Now the passenger version looks like this: "Phusion Passenger(R) 6.0.8".
So the regex is not working for the "(R)".

**Comment by betesh** [comment]
Fixed by #53
