### ISSUE TITLE
Problem running capistrano passenger with asdf

### ISSUE THREAD

**Issue by Startouf** [capistrano/passenger#56]
asdf is a multi-tool manager that can handle ruby, node, etc.

They also have a capistrano package that add hooks during deployment

https://github.com/cabesa-collective/capistrano-asdf

It seems like it does not work well with capistrano passenger and cannot find the bundle

```
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as xxx: passenger exit status: 127
passenger stdout: Nothing written
passenger stderr: bash: line 1: bundle: command not found


Caused by:
SSHKit::Command::Failed: passenger exit status: 127
passenger stdout: Nothing written
passenger stderr: bash: line 1: bundle: command not found

Tasks: TOP => passenger:restart
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as xxx passenger stdout: Nothing written
passenger stderr: bash: line 1: bundle: command not found
```

However the same command on my server with the same user works

```
cd /websites/xxx/releases/20220308104110 && bundle exec passenger -v
# Phusion Passenger(R) 6.0.12
```

**Comment by will-in-wi** [comment]
I use asdf, but not that Capistrano plugin.

Looking at the source for the asdf Capistrano plugin, it looks like they prepend the asdf source file only to things listed in `asdf_map_ruby_bins`, which defaults to just a couple of basic things.

https://github.com/cabesa-collective/capistrano-asdf/blob/master/lib/capistrano/tasks/asdf.rake#L4

https://github.com/cabesa-collective/capistrano-asdf/blob/master/lib/capistrano/tasks/asdf.rake#L39-L40

I think if you added the following to your `deploy.rb`, it might resolve the issue:
```ruby
append :asdf_map_ruby_bins, 'passenger-config'
```

If this works, I'd encourage you to make a PR against the asdf capistrano plugin to add some documentation for this use case (or add the `passenger-config` binary to the default list).

**Comment by will-in-wi** [comment]
I'm closing this. Feel free to reopen if that solution doesn't work for you.

**Comment by Startouf** [comment]
Yes you're right, I ended up adding `set :asdf_map_ruby_bins, %w[rake bundle gem ruby passenger passenger-config]` and it works like a charm, I'll add a note to the readme if it's okay with you
